server.port=3000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

logging.level.root=warn
logging.level.org.springframework=warn
logging.level.org.hibernate=error
logging.level.blessmysoulbackend.rest=info

spring.cache.caffeine.spec=maximumSize=10000,expireAfterAccess=360s