spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

logging.level.root=warn
logging.level.org.springframework=warn
logging.level.org.hibernate=error
logging.level.blessmysoulbackend.rest=info